stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - raw_data.csv
    outs:
      - processed_data.csv

  train:
    cmd: python train_model.py
    deps:
      - processed_data.csv
    outs:
      - model.pkl 