name: CI Pipeline

on:
  push:
    branches:
      - test

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install lint dependencies
        run: |
          pip install -r requirements-lint.txt

      - name: Lint code
        run: |
          flake8 .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install test dependencies
        run: |
          pip install -r requirements-lint.txt

      - name: Run tests
        run: |
          pytest
